modLoader="javafml"
loaderVersion="4,"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="MrPup(minecraftkus)"

description='''
API for MrPup(minecraftkus) mods
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
