license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="MrPup(minecraftkus)"

description='''
API for MrPup(minecraftkus) mods
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.21-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

